// Shared presentation only; all scores continue to come from the existing engine.
function unifiedDetailHtml(id) {
 const k=getEffectiveKpi(id),q=dtlQuarter,leaf=k.isLeaf;
 const score=qq=>leaf?scoreAt(id,qq):scoreParentAt(id,qq);
 const s=score(q),fc=forecastHomeScore(id),forecast=MOU_DATA.forecast[id];
 const report=publishedQuarterReport(id,q),children=ovpChildren(id),leaves=reportLeaves(id);
 const filled=leaves.filter(c=>getPublicQuarterInput(c.id,q)!==null).length;
 const esc=v=>entryEsc(v===null||v===undefined||v===''?'-':String(v));
 const num=v=>v===null||v===undefined?'-':typeof v==='number'?ovpFmt(v):esc(v);
 const level=v=>v===null||v===undefined?'-':Number(v).toFixed(4);
 const actual=qq=>leaf?reportValueText(id,qq).replaceAll('—','-'):'-';
 const useMonthly=NUMERIC_DETAIL_IDS.includes(id);
 const method=k.scoringMethod,stepType=['milestone_pct','milestone_manual','qualitative','evidence'].includes(method);
 const thresholds=k.thresholds||[],target=thresholds[4];
 const numericTarget=leaf&&!stepType&&typeof target==='number'&&Number.isFinite(target);
 const color=s.level===null?LV_COLORS[null]:lvColor(s.level);
 const periods={q1:'ต.ค. – ธ.ค. 68',q2:'ม.ค. – มี.ค. 69',q3:'เม.ย. – มิ.ย. 69',q4:'ก.ค. – ก.ย. 69'};
 const summary=reportText(id,q,'summary_text')||MOU_DATA.quarterly[id]?.[q]?.note||'-';
 const obstacle=reportText(id,q,'obstacle_text')||'-',action=reportText(id,q,'solution_text')||'-';
 const activities=MOU_DATA.activities[id]?.steps||[];
 const quarterRows=QUARTERS.map(qq=>`<tr class="${qq===q?'current-q':''}"><td>${Q_LABEL[qq]}</td><td>${actual(qq)}</td><td>${ovpBadge(score(qq).level)}</td><td>${ovpBadge(k.targetScore)}</td></tr>`).join('');
 const childRows=children.map(c=>{const cs=c.isLeaf?scoreAt(c.id,q):scoreParentAt(c.id,q);return `<tr><td><button class="fp-kpi-link" onclick="dtlGoTo('${c.id}')">${esc(c.id)} · ${esc(c.label)} →</button></td><td>${c.isLeaf?reportValueText(c.id,q):'-'}</td><td>${ovpBadge(cs.level)}</td></tr>`;}).join('');
 const criteria=thresholds.some(t=>t!==null&&t!==undefined)?`<div class="fp24-thresholds">${thresholds.map((t,i)=>`<span>ระดับ ${i+1}<b>${num(t)}${method==='milestone_pct'&&typeof t==='number'?` (${num(t*100)}%)`:''}</b></span>`).join('')}</div>`:'<p>-</p>';
 const trendData=QUARTERS.map((qq,i)=>({i,v:score(qq).level}));
 const d=trendData.map((p,i)=>p.v===null?'':`${i&&trendData[i-1].v!==null?'L':'M'}${65+p.i*190},${175-p.v*28}`).join(' ');
 const trend=`<svg class="fp-score-chart" viewBox="0 0 700 215" role="img" aria-label="แนวโน้มคะแนนรายไตรมาส"><line x1="65" x2="635" y1="35" y2="35" stroke="#9aaabd" stroke-dasharray="5 5"/>${[1,2,3,4,5].map(v=>`<line x1="65" x2="635" y1="${175-v*28}" y2="${175-v*28}" stroke="#edf0f3"/><text x="43" y="${179-v*28}">${v}</text>`).join('')}<path d="${d}" fill="none" stroke="#41a570" stroke-width="3"/>${trendData.map(p=>`<text x="${65+p.i*190}" y="200" text-anchor="middle">Q${p.i+1}</text>${p.v===null?'':`<circle cx="${65+p.i*190}" cy="${175-p.v*28}" r="5" fill="#41a570"><title>คะแนน ${level(p.v)}</title></circle>`}`).join('')}</svg>`;
 const evidence=reportEvidenceHtml(report).replace('ยังไม่มีเอกสารแนบ','-');
 const breakdown=report?.values&&REPORT_FIELDS[id]?REPORT_FIELDS[id].fields.map(([key,label])=>`<div class="dtl-support-item"><div class="dtl-support-label">${esc(label)}</div><div class="dtl-support-val">${esc(report.values[key])}</div></div>`).join(''):'';
 const scoreNote=s.level===null?'-':`คะแนน${leaf?'ปัจจุบัน':'รวมจากข้อย่อยที่มีข้อมูล'} ${level(s.level)} จากคะแนนเต็ม 5`;
 return `<div class="fp24-heading"><div><span class="fp24-eyebrow">KPI DETAIL · ${esc(id)}</span><h1>รายละเอียดตัวชี้วัด</h1><p>แสดงผลการดำเนินงาน ค่าเป้าหมาย แนวโน้ม และข้อสังเกตในแต่ละไตรมาส</p></div><span class="fp24-year">ปีงบประมาณ 2569</span></div>
 <div class="fp24-grid">
 <section class="fp24-card fp24-info"><h2>ข้อมูลตัวชี้วัด</h2><dl><div><dt>รหัสตัวชี้วัด</dt><dd>${esc(id)}</dd></div><div><dt>ชื่อตัวชี้วัด</dt><dd>${esc(k.label)}</dd></div><div><dt>ประเภทของตัวชี้วัด :</dt><dd><span class="fp24-type">${esc(k.groupLabel)}</span></dd></div><div><dt>น้ำหนัก / หน่วยวัด</dt><dd>${num(k.weight)}% · ${esc(k.unit)}</dd></div><div><dt>ผู้รับผิดชอบหลัก</dt><dd>${esc((k.ownerMain||[]).join(', '))}</dd></div></dl></section>
 <div class="fp24-top"><div class="fp24-quarters" aria-label="เลือกไตรมาส">${QUARTERS.map(qq=>`<button type="button" class="${q===qq?'selected':''} ${score(qq).level===null?'pending':''}" onclick="dtlSetQuarter('${qq}')" aria-pressed="${q===qq}"><b>${Q_LABEL[qq]}</b><span>${periods[qq]}</span>${score(qq).level===null?'<small>รอข้อมูล</small>':''}</button>`).join('')}</div>
 <section class="fp24-card fp24-metrics" style="--fp24-score-color:${color}"><div><h3>${leaf?'ผลการดำเนินงาน':'คะแนนรวมข้อย่อย'}</h3><strong class="fp-result">${leaf?actual(q):level(s.level)}</strong><small>${leaf?esc(k.unit):'/ 5'}</small><p>${leaf?Q_LABEL[q]:`มีผล ${filled}/${leaves.length} ข้อย่อย`}</p></div><div><h3>${numericTarget?'เกณฑ์ระดับ 5':'คะแนนเป้าหมาย'}</h3><strong>${numericTarget?num(target):num(k.targetScore)}</strong><small>${numericTarget?esc(k.unit):'/ 5'}</small><p>${numericTarget?(k.higherIsBetter===false?'ค่ายิ่งต่ำยิ่งดี':'ค่ายิ่งสูงยิ่งดี'):'ตามเกณฑ์ตัวชี้วัด'}</p></div><div><h3>คะแนนที่ได้</h3><strong style="color:${color}">${level(s.level)}</strong><small>/ 5</small><p>${filled<leaves.length?'ข้อมูลยังไม่ครบ':Q_LABEL[q]}</p></div></section></div>
 <section class="fp24-card fp24-progress"><h2>${useMonthly?'ความก้าวหน้าต่อเป้าหมายสิ้นปี ('+Q_LABEL[q]+')':leaf?'เกณฑ์การประเมิน':'สรุปคะแนนรวมข้อย่อย'}</h2>${useMonthly?numericProgress(id,q):''}<p>${esc(scoreNote)}</p>${leaf?criteria:`<p>มีผล ${filled}/${leaves.length} ข้อย่อย · คะแนนรวมคำนวณตามน้ำหนักของข้อย่อยที่มีข้อมูล</p>`}${k.needsConfirmation?`<p class="fp-rule-note">${esc(k.confirmationNote)}</p>`:''}<div class="fp-forecast"><span>คาดการณ์สิ้นปี</span><b>${leaf?num(forecast?.result):'-'} ${leaf?esc(k.unit):''}</b><span>คะแนนคาดการณ์ <b>${level(fc?.level)}</b> / 5</span></div></section>
 <section class="fp24-card fp24-chart"><h2>${useMonthly?'แนวโน้มผลการดำเนินงานรายเดือน':children.length?'ตัวชี้วัดย่อย':stepType?'แผนงาน / ขั้นตอนตามข้อมูลต้นทาง':'แนวโน้มคะแนนรายไตรมาส'}</h2>${useMonthly?numericMonthlyChart(id,q):children.length?`<div class="fp24-table-scroll"><table class="dtl-qtable"><thead><tr><th>ตัวชี้วัด</th><th>ผล</th><th>คะแนน</th></tr></thead><tbody>${childRows}</tbody></table></div>`:stepType?(activities.length?`<ol class="fp-step-list">${activities.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p class="fp-rule-note">แสดงขั้นตอนตามแผน; สถานะสำเร็จใช้รายงานที่ยืนยัน</p>`:'<p>-</p>'):trend}</section>
 <section class="fp24-card fp24-notes"><h2>ข้อสังเกตและข้อเสนอแนะ</h2><p>${esc(summary)}</p><div class="fp24-next"><h3>ปัญหา / อุปสรรค</h3><p>${esc(obstacle)}</p></div><div class="fp24-next"><h3>แนวทางการดำเนินงาน</h3><p>${esc(action)}</p></div></section>
 <section class="fp24-card fp24-comparison"><h2>เปรียบเทียบรายไตรมาส</h2><div class="fp24-table-scroll"><table class="dtl-qtable"><thead><tr><th>ไตรมาส</th><th>ผลการดำเนินงาน</th><th>คะแนน</th><th>คะแนนเป้าหมาย</th></tr></thead><tbody>${quarterRows}</tbody></table></div><p class="fp24-footnote">${leaf?'แสดงผลตามวิธีวัดของตัวชี้วัด':'คะแนนรวมจากข้อย่อยที่มีข้อมูล'}</p><div class="dtl-forecast-row">คะแนนคาดการณ์สิ้นปี <b>${level(fc?.level)}</b></div></section></div>
 ${useMonthly&&children.length?`<section class="dtl-section-card"><div class="card-title">ตัวชี้วัดย่อย</div><table class="dtl-qtable"><thead><tr><th>ตัวชี้วัด</th><th>ผล</th><th>คะแนน</th></tr></thead><tbody>${childRows}</tbody></table></section>`:''}<section class="dtl-section-card"><div class="card-title">ข้อมูลสนับสนุน</div><div class="dtl-support-grid"><div class="dtl-support-item"><div class="dtl-support-label">คำจำกัดความ</div><div class="dtl-support-val">${esc(k.definition)}</div></div><div class="dtl-support-item"><div class="dtl-support-label">วิธีการคำนวณ</div><div class="dtl-support-val">${esc(k.calculationMethod)}</div></div><div class="dtl-support-item"><div class="dtl-support-label">เอกสารแนบ</div><div class="dtl-support-val">${evidence}</div></div><div class="dtl-support-item"><div class="dtl-support-label">คำอธิบายการคาดการณ์</div><div class="dtl-support-val">${esc(forecast?.note)}</div></div>${breakdown}</div>${(MOU_DATA.deductions||[]).filter(d=>d.kpi===id).map(d=>`<p>เงื่อนไขหักคะแนน: ${esc(d.reason)}</p>`).join('')}${(MOU_DATA.assignments||[]).filter(d=>d.kpi===id).map(d=>`<p>มติ / ข้อสั่งการ: ${esc(d.note)}</p>`).join('')}<button class="fp-kpi-link" onclick="reportToEntry('${id}')">ไปกรอกผล Q3 →</button></section>`;
}
